### ISSUE TITLE
error compiling imglab tool

### ISSUE THREAD

**Issue by zhuoc** [davisking/dlib#41]
When I  try to compile the imglab tool provided with dlib following the instructions, I got this error:

[ 89%] Building CXX object CMakeFiles/imglab.dir/src/main.cpp.o
In file included from /home/zhuoc/Packages/Dlib/dlib/dlib/../dlib/data_io/../algs.h:75:0,
                 from /home/zhuoc/Packages/Dlib/dlib/dlib/../dlib/data_io/libsvm_io.h:11,
                 from /home/zhuoc/Packages/Dlib/dlib/dlib/../dlib/data_io.h:6,
                 from /home/zhuoc/Packages/Dlib/dlib/tools/imglab/src/main.cpp:2:
/home/zhuoc/Packages/Dlib/dlib/dlib/../dlib/data_io/../image_saver/save_png.h: In instantiation of ‘typename dlib::disable_if<dlib::is_matrix<image_type> >::type dlib::save_png(const image_type&, const string&) [with image_type = dlib::array2d<dlib::rgb_pixel>; typename dlib::disable_if<dlib::is_matrix<image_type> >::type = void; std::string = std::basic_string<char>]’:
/home/zhuoc/Packages/Dlib/dlib/tools/imglab/src/main.cpp:301:32:   required from here
/home/zhuoc/Packages/Dlib/dlib/dlib/../dlib/data_io/../assert.h:76:53: error: incomplete type ‘dlib::compile_time_assert<false>’ used in nested name specifier
         DLIB_NO_WARN_UNUSED typedef char BOOST_JOIN(DLIB_CTA, __LINE__)[::dlib::compile_time_assert<(bool)(expression)>::value]

I'm working on Ubuntu14.04. I have built all examples with no problem. Did I do anything wrong with this?

**Comment by davisking** [comment]
Try running cmake again.  Does that fix it?

**Comment by davisking** [comment]
Actually, I think this was a bug in the dlib cmake files which should now be fixed.  If you repull the code from github it should work without issue now.

**Comment by zhuoc** [comment]
Yes now it builds without any problem. Thanks for the quick response!
