### ISSUE TITLE
Dlib 19.21 not compile with Visual Studio 2019 v19.1 - cuda_dlib.cu Error

### ISSUE THREAD

**Issue by sergiogut1805** [davisking/dlib#2323]
**Dlib 19.21**
**Windows 10**
**Visual Studio 2019 v19.1**
**CUDA 10.1**
**Cudnn 7.6.5**

Dlib compile OK up to 18.6 versión, after 19 update (19.0, 19.1) throw this error in any example program:

Compilation error:
Operación Compilar iniciada..
1>------ Operación Compilar iniciada: proyecto: ZERO_CHECK, configuración: Release x64 ------
1>Checking Build System
2>------ Operación Compilar iniciada: proyecto: dlib, configuración: Release x64 ------
2>Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cuda_dlib.cu.obj
2>cuda_dlib.cu
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1497): error : calling a __host__ function("__floorf") from a __global__ function("dlib::cuda::_cuda_resize_bilinear") is not allowed
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1497): error : identifier "__floorf" is undefined in device code
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1502): error : calling a __host__ function("__floorf") from a __global__ function("dlib::cuda::_cuda_resize_bilinear") is not allowed
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1502): error : identifier "__floorf" is undefined in device code
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1534): error : calling a __host__ function("__floorf") from a __global__ function("dlib::cuda::_cuda_resize_bilinear_strided") is not allowed
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1534): error : identifier "__floorf" is undefined in device code
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1539): error : calling a __host__ function("__floorf") from a __global__ function("dlib::cuda::_cuda_resize_bilinear_strided") is not allowed
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1539): error : identifier "__floorf" is undefined in device code
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1608): error : calling a __host__ function("__floorf") from a __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient") is not allowed
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1608): error : identifier "__floorf" is undefined in device code
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1613): error : calling a __host__ function("__floorf") from a __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient") is not allowed
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1613): error : identifier "__floorf" is undefined in device code
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1644): error : calling a __host__ function("__floorf") from a __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient_strided") is not allowed
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1644): error : identifier "__floorf" is undefined in device code
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1649): error : calling a __host__ function("__floorf") from a __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient_strided") is not allowed
2>
2>C:/MLCNN/dlib-19.21/dlib/cuda/cuda_dlib.cu(1649): error : identifier "__floorf" is undefined in device code
2>
2>16 errors detected in the compilation of "C:/Users/sergi/AppData/Local/Temp/tmpxft_00003174_00000000-10_cuda_dlib.cpp1.ii".
2>cuda_dlib.cu
2>CMake Error at dlib_generated_cuda_dlib.cu.obj.Release.cmake:280 (message):
2>  Error generating file C:/MLCNN/Dlib
2>  Compiled/dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cuda_dlib.cu.obj
2>
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Compilación personalizada de "C:\MLCNN\dlib-19.21\dlib\cuda\cuda_dlib.cu;C:\MLCNN\dlib-19.21\dlib\cuda\cusolver_dlibapi.cu" terminada con el código 1.
2>Compilación del proyecto "dlib.vcxproj" terminada -- ERROR.
3>------ Operación Compilar iniciada: proyecto: webcam_face_pose_ex, configuración: Release x64 ------
3>Building Custom Rule C:/MLCNN/dlib-19.21/examples/CMakeLists.txt
3>webcam_face_pose_ex.cpp
3>LINK : fatal error LNK1181: no se puede abrir el archivo de entrada 'dlib_build\Release\dlib19.21.0_release_64bit_msvc1928.lib'
3>Compilación del proyecto "webcam_face_pose_ex.vcxproj" terminada -- ERROR.
========== Compilar: 1 correctos, 2 incorrectos, 0 actualizados, 0 omitidos ==========

I tried compile newly DLIB in clean way but the error appears again.

if i dowgrade the Visual Studio 2019 to 18.6 versión or inferior versión all works fine, but i should stop the update service because it updates the compiler and the error goes again.

**Comment by sergiogut1805** [comment]
**Update**: I try with CUDA 11.2 and Cuddn 8.1 and fails again.

But if i remove CUDA and compile on Visual studio v19.1 without it, DLIB runs OK.

Obviously without CUDA DLIB is inusable for train models or do quick inferences in DNN.

**Comment by davisking** [comment]
Try the latest dlib from github.

**Comment by sergiogut1805** [comment]
> Try the latest dlib from github.

Problem Solved 👌

Thanks Davis!

**Comment by gaurav7700** [comment]
> > Try the latest dlib from github.
> 
> Problem Solved 👌
> 
> Thanks Davis!

Hi how did you solved the issue??

**Comment by sergiogut1805** [comment]
> > > Try the latest dlib from github.
> > 
> > 
> > Problem Solved 👌
> > Thanks Davis!
> 
> Hi how did you solved the issue??

Easy, compile the latest versión of DLIB in Github repository (19.21.99)

Davis has fixed the problem.

**Comment by Hakentha** [comment]
I have same problem with an rtx3090 windows 10, i try cuda 10.0/1/2 11.0/1/2 and cdnn 7/8 no problem in compile. but when i run th eproject trow me error in cudnn_dlibapi.cpp.
I run the same project with an rtx2070 and works perfect.
