### ISSUE TITLE
Undefined references in libdlib.a

### ISSUE THREAD

**Issue by pi-null-mezon** [davisking/dlib#1279]
I am working on Ubuntu 16.04 x64. Recently I have updated my system to CUDA 9.1 version and cudnn 7.1 version along with the new NVidia GPU driver 390.48. I should note that after installation all CUDA samples build and run properly. And I have successfully rebuild dlib library with CUDA support enabled. But... all my apps linked with the libdlib stop to compile. Compiler just says:
````
g++ -Wl,-O1 -o ../../bin/Trainer main.o   -L/usr/local/cuda-9.1/lib64 -L/usr/lib/x86_64-linux-gnu -lcudnn -lpthread -ldlib -L/usr/local/lib -lopencv_core -lopencv_objdetect -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lopencv_imgcodecs -lopencv_dnn 
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_descriptor::set_size(int, int, int, int)':
cudnn_dlibapi.cpp:(.text+0x4b): undefined reference to `cudnnDestroyTensorDescriptor'
cudnn_dlibapi.cpp:(.text+0x6f): undefined reference to `cudnnCreateTensorDescriptor'
cudnn_dlibapi.cpp:(.text+0x99): undefined reference to `cudnnSetTensor4dDescriptor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_descriptor::get_size(int&, int&, int&, int&) const':
cudnn_dlibapi.cpp:(.text+0x3de): undefined reference to `cudnnGetTensor4dDescriptor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_conv::clear()':
cudnn_dlibapi.cpp:(.text+0x5c3): undefined reference to `cudnnDestroyFilterDescriptor'
cudnn_dlibapi.cpp:(.text+0x5d1): undefined reference to `cudnnDestroyConvolutionDescriptor'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_conv::~tensor_conv()':
cudnn_dlibapi.cpp:(.text+0x913): undefined reference to `cudnnDestroyFilterDescriptor'
...(over 1000 strings with the same looking errors)
````

Please, give me advice, what should I do to resolve this issue? 
  
* **Version**: master at 27.04.2018
* **Where did you get dlib**: here, on github
* **Platform**: Ubuntu 16.04.4 LTS x64
* **Compiler**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9)

**Comment by davisking** [comment]
Put -ldlib before -lcudnn

**Comment by pi-null-mezon** [comment]
Still get same error:
````
g++ -Wl,-O1 -o ../../bin/Trainer main.o   -L/usr/local/cuda-9.1/lib64 -L/usr/lib/x86_64-linux-gnu -ldlib -lcudnn -lpthread -L/usr/local/lib -lopencv_core -lopencv_objdetect -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lopencv_imgcodecs -lopencv_dnn 
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_conv::get_gradient_for_data(bool, dlib::tensor const&, dlib::tensor const&, dlib::tensor&)':
cudnn_dlibapi.cpp:(.text+0xaba7): undefined reference to `cudaGetDevice'
cudnn_dlibapi.cpp:(.text+0xb170): undefined reference to `cudaGetErrorString'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::tensor_conv::get_gradient_for_filters(bool, dlib::tensor const&, dlib::tensor const&, dlib::tensor&)':
cudnn_dlibapi.cpp:(.text+0xb5cf): undefined reference to `cudaGetDevice'
cudnn_dlibapi.cpp:(.text+0xbb98): undefined reference to `cudaGetErrorString'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::assign_conv_bias_gradient(dlib::tensor&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0xc002): undefined reference to `cudaGetDevice'
cudnn_dlibapi.cpp:(.text+0xc37d): undefined reference to `cudaGetErrorString'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::pooling::get_gradient(dlib::tensor const&, dlib::tensor const&, dlib::tensor const&, dlib::tensor&)':
cudnn_dlibapi.cpp:(.text+0xc9ff): undefined reference to `cudaGetDevice'
cudnn_dlibapi.cpp:(.text+0xcd97): undefined reference to `cudaGetErrorString'
/usr/local/lib/libdlib.a(cudnn_dlibapi.cpp.o): In function `dlib::cuda::batch_normalize_conv_inference(double, dlib::resizable_tensor&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&, dlib::tensor const&)':
cudnn_dlibapi.cpp:(.text+0xd72f): undefined reference to `cudaGetDevice'
cudnn_dlibapi.cpp:(.text+0xda0f): undefined reference to `cudaGetErrorString'
...
````

**Comment by davisking** [comment]
Oh, you are linking to the static library.  You also need to link to the cuda runtime.  Those are cuda symbols, so you need to link to the cuda libraries that contain them.  

If you installed dlib as a shared library you could just do -ldlib and it would pull in the right libraries, but since you are trying to link to a static library you aren't getting those automatically and have to link them yourself.  But really, you should either use cmake or install dlib as a shared library if you insist on not using cmake.

**Comment by pi-null-mezon** [comment]
Thank you @davisking. My problem has been solved by the manual addition of cuda libraries in linking section of project:
````
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -fPIC -DPATH_TO_DLIB_RES=\"\" -DOPENCV_DIR=\"\" -I../../Learner -I. -I/home/alex/Programming/Kaggle/Shared/dlibimgaugment -I/home/alex/Programming/Kaggle/Shared/opencvimgaugment -I/home/alex/Programming/Kaggle/Shared/dlibopencvconverter -I/home/alex/Qt/5.10.0/gcc_64/mkspecs/linux-g++ -o main.o ../../Learner/main.cpp
g++ -Wl,-O1 -o ../../bin/Trainer main.o   -ldlib -L/usr/local/cuda-9.1/lib64 -lcudnn -lpthread -lcuda -lcudart -lcublas -lcurand -lcusolver -lopencv_core -lopencv_objdetect -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lopencv_imgcodecs -lopencv_dnn
````
