### ISSUE TITLE
dlib v19.22 (and master) does not build with gcc 4.8.5 on CentOS 7

### ISSUE THREAD

**Issue by cweigel** [davisking/dlib#2354]
## Expected Behavior
`$ python setup.py build` shall succeed even with gcc 4.8.5 since centos 7 is still around and the compiler is not rejected in the `CMakeLists.txt `.

## Current Behavior
`$ python setup.py build` fails 

### Compile Issue 1

during CMake run there is a first hint during CUDA test compile:

```cmake
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.
-- *** The output of the failed CUDA test compile is shown below:
-- ***
-- ***   Change Dir: /build-dlib/dlib/build/dlib/cuda_test_build
   ***
   ***   Run Build Command(s):/usr/bin/gmake && [ 50%] Building NVCC (Device) object CMakeFiles/cuda_test.dir/cuda_test_generated_cuda_test.cu.o
   ***   /build-dlib/dlib/dlib/cmake_utils/test_for_cuda/../../cuda/../matrix/../vectorstream/vectorstream.h:31:24: error: invalid use of dependent type 'dlib::vectorstream::vector_streambuf<CharType>::size_type'
   ***                size_type read_pos = 0; // buffer[read_pos] == next byte to read from buffer
   ***                           ^
   ***   CMake Error at cuda_test_generated_cuda_test.cu.o.cmake:276 (message):
   ***     Error generating file
   ***     /build-dlib/dlib/build/dlib/cuda_test_build/CMakeFiles/cuda_test.dir//./cuda_test_generated_cuda_test.cu.o
```

The  problem which gcc 4.8.5 complains about is initialization of the typedef'd `size_type` this line 31 in `dlib/vectorstream/vectorstream.h`. 

```
 size_type read_pos = 0; // buffer[read_pos] == next byte to read from buffer
```
for which gcc 4.8.5 gives this error:
```
[...]/dlib/dlib/threads/../binary_search_tree/../vectorstream/vectorstream.h:31:34: error: invalid use of dependent type 'dlib::vectorstream::vector_streambuf<CharType>::size_type'
```

This can be fixed by not initializing `read_pos`:

```
 size_type read_pos; // buffer[read_pos] == next byte to read from buffer
```
which should to no harm since it is initialized in the constructor as well.

### Compile Issue 2

However, when fixing compile issue 1 this issue shows up:

```cmake
[ 68%] Building CXX object dlib_build/CMakeFiles/dlib.dir/cuda/gpu_data.cpp.o
In file included from /build-dlib/dlib/dlib/filtering/../global_optimization.h:8:0,
                 from /build-dlib/dlib/dlib/filtering/kalman_filter.cpp:7:
/build-dlib/dlib/dlib/filtering/../global_optimization/find_max_global.h:284:47: error: default argument missing for parameter 8 of 'template<class funct, class ... Args> std::pair<long unsigned int, dlib::function_evaluation> dlib::impl::find_max_global(double, dlib::thread_pool&, std::vector<_RealType>&, std::vector<dlib::function_spec>, std::chrono::nanoseconds, dlib::max_function_calls, double, Args&& ...)'
         std::pair<size_t,function_evaluation> find_max_global (
                                               ^
/build-dlib/dlib/dlib/filtering/../global_optimization/find_max_global.h:303:47: error: default argument missing for parameter 7 of 'template<class funct, class ... Args> std::pair<long unsigned int, dlib::function_evaluation> dlib::impl::find_max_global(double, dlib::thread_pool&, std::vector<_RealType>&, std::vector<dlib::function_spec>, std::chrono::nanoseconds, double, Args&& ...)'
         std::pair<size_t,function_evaluation> find_max_global (
                                               ^
In file included from /build-dlib/dlib/dlib/svm/../global_optimization.h:8:0,
                 from /build-dlib/dlib/dlib/svm/auto.cpp:7:
/build-dlib/dlib/dlib/svm/../global_optimization/find_max_global.h:284:47: error: default argument missing for parameter 8 of 'template<class funct, class ... Args> std::pair<long unsigned int, dlib::function_evaluation> dlib::impl::find_max_global(double, dlib::thread_pool&, std::vector<_RealType>&, std::vector<dlib::function_spec>, std::chrono::nanoseconds, dlib::max_function_calls, double, Args&& ...)'
         std::pair<size_t,function_evaluation> find_max_global (
                                               ^
/build-dlib/dlib/dlib/svm/../global_optimization/find_max_global.h:303:47: error: default argument missing for parameter 7 of 'template<class funct, class ... Args> std::pair<long unsigned int, dlib::function_evaluation> dlib::impl::find_max_global(double, dlib::thread_pool&, std::vector<_RealType>&, std::vector<dlib::function_spec>, std::chrono::nanoseconds, double, Args&& ...)'
         std::pair<size_t,function_evaluation> find_max_global (
                                               ^
```

Seems that the "old" gcc cannot cope with variadic/Parameter pack? function declaration (probably because there is a default value set before for `solver_epsilon `(line 291):

```cpp
        std::pair<size_t,function_evaluation> find_max_global (
    285             double ymult,
    286             thread_pool& tp,
    287             std::vector<funct>& functions,
    288             std::vector<function_spec> specs,
    289             const std::chrono::nanoseconds max_runtime,
    290             const max_function_calls num,
    291             double solver_epsilon = 0,
    292             Args&& ...args
    293         )

```
Unfortunately I could not find a solution for that yet...

## Steps to Reproduce
run 
```
`$ python setup.py build` 
``` 
with gcc 4.8.5

* **Version**: v19.22 and current master
* **Where did you get dlib**: GitHub repository
* **Platform**: CentOS 7 base on nvidia/cuda docker image: nvidia/cuda:10.0-cudnn7-devel-centos7 + dev tools
* **Compiler**: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

**Comment by arrufat** [comment]
Yeah, dlib v19.22 dropped support for gcc 4.8, try with a previous version.

**Comment by cweigel** [comment]
That's a pity. There are still a lot of CentOS 7 installations out there and it will get maintenance update until 2024. However, if this is the decision we have to live with it. Yet it would be good to write this to the `README.md` or/and catch it by the CMake run.

Thx anyway. Keep up the great work.

**Comment by arrufat** [comment]
It's not like you can't use dlib anymore, just install v19.21 :)

**Comment by davisking** [comment]
Heh, yeah, I try and go wack by with compiler support.  But it's 2021 and I've only moved dlib to C++11.  And even then I've tried to avoid breaking compilers that have only partial C++11 support.   But gcc 4.8.5 is just too non-C++11 compliant at this point to be tenable.

And like @arrufat pointed out.  Just don't upgrade to the newest dlib version and you are good.

**Comment by cweigel** [comment]
Thx for your feedback - closing the issue.
