### ISSUE TITLE
webcam_face_pose_ex.cpp does not build on Jetson Nano Jetpack 4.4.1

### ISSUE THREAD

**Issue by George056** [davisking/dlib#2291]
I am working on an Nvidia Jetson Nano and trying to use dlib in conjunction with OpenCV on a project. I am trying to perform something that can use the webcam_face_pose_ex.cpp as a potential base to build off of and am receiving an error when I try to compile it with CMake.

I have checked and am able to compile a project that just uses OpenCV or just dlib. I also have confirmed that other examples that have a gui did build. Other previous issues related to this did not help.

## Expected Behavior
I expect the program to compile and be able to be ran. GUI, OpenCV, and Facial Detection.

## Current Behavior

A compilation error occurs.

[ 53%] Building CXX object CMakeFiles/webcam_face_pose_ex.dir/webcam_face_pose_ex.cpp.o
In file included from /home/cervpro/dlib-19.6/dlib/../dlib/opencv.h:10:0,
                 from /home/cervpro/dlib-19.6/examples/webcam_face_pose_ex.cpp:30:
/home/cervpro/dlib-19.6/dlib/../dlib/opencv/cv_image.h: In instantiation of ‘dlib::cv_image<pixel_type>::cv_image(cv::Mat) [with pixel_type = dlib::bgr_pixel]’:
/home/cervpro/dlib-19.6/examples/webcam_face_pose_ex.cpp:73:42:   required from here
/home/cervpro/dlib-19.6/dlib/../dlib/opencv/cv_image.h:37:22: error: conversion from ‘const cv::Mat’ to non-scalar type ‘IplImage {aka _IplImage}’ requested
             IplImage temp = img;
                      ^~~~
CMakeFiles/webcam_face_pose_ex.dir/build.make:62: recipe for target 'CMakeFiles/webcam_face_pose_ex.dir/webcam_face_pose_ex.cpp.o' failed
make[2]: *** [CMakeFiles/webcam_face_pose_ex.dir/webcam_face_pose_ex.cpp.o] Error 1
CMakeFiles/Makefile2:1547: recipe for target 'CMakeFiles/webcam_face_pose_ex.dir/all' failed
make[1]: *** [CMakeFiles/webcam_face_pose_ex.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

## Steps to Reproduce
Running CMake as instructed on http://dlib.net/compile.html for CMake on a Jetson Nano (with Jetpack version 4.4.1).

* **Version**: 19.6
* **Where did you get dlib**: dlib.net
* **Platform**: Jetson Nano, Jetpack 4.4.1
* **Compiler**: CMake, g++ 7.5.0

**Comment by arrufat** [comment]
Hi, what version of OpenCV are you using?
I think you should try dlib v19.20 or newer, since it supports new versions of OpenCV that don't have `IplImage` any more.

**Comment by George056** [comment]
I have OpenCV 4.5.0

**Comment by arrufat** [comment]
So, yes, you should use dlib v19.20 or newer.

**Comment by George056** [comment]
Great, I got it working. Thanks for the help.
