### ISSUE TITLE
Moving from gcc 5.4 to 7.3 breaks 

### ISSUE THREAD

**Issue by achalshah20** [davisking/dlib#1280]
I have upgraded gcc from 5.xx to 7.xx. I recompiled dlib and it compiles successfully.  But when I try to compile the same code which was working fine with gcc 5, it breaks.

## Expected Behavior
Code should compiles and works as expected.

## Current Behavior
```
In file included from /usr/include/dlib/matrix.h:19:0,
                 from /usr/include/dlib/statistics/statistics.h:10,
                 from /usr/include/dlib/statistics.h:6,
                 from /usr/include/dlib/image_transforms/assign_image.h:8,
                 from /usr/include/dlib/image_loader/image_loader.h:15,
                 from /usr/include/dlib/image_io.h:11,
                 from /xx/xxx/xxx.cpp:8:
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_axpy(int, const std::complex<float>&, const std::complex<float>*, int, std::complex<float>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:164:52: error: cannot convert ‘const std::complex<float>*’ to ‘const float*’ for argument ‘2’ to ‘void cblas_caxpy(blasint, const float*, const float*, blasint, float*, blasint)’
             cblas_caxpy(N, &alpha, X, incX, Y, incY);
                                                    ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_axpy(int, const std::complex<double>&, const std::complex<double>*, int, std::complex<double>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:171:52: error: cannot convert ‘const std::complex<double>*’ to ‘const double*’ for argument ‘2’ to ‘void cblas_zaxpy(blasint, const double*, const double*, blasint, double*, blasint)’
             cblas_zaxpy(N, &alpha, X, incX, Y, incY);
                                                    ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_scal(int, const std::complex<float>&, std::complex<float>*)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:191:40: error: cannot convert ‘const std::complex<float>*’ to ‘const float*’ for argument ‘2’ to ‘void cblas_cscal(blasint, const float*, float*, blasint)’
             cblas_cscal(N, &alpha, X, 1);
                                        ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_scal(int, const std::complex<double>&, std::complex<double>*)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:197:40: error: cannot convert ‘const std::complex<double>*’ to ‘const double*’ for argument ‘2’ to ‘void cblas_zscal(blasint, const double*, double*, blasint)’
             cblas_zscal(N, &alpha, X, 1);
                                        ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_gemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, const std::complex<float>&, const std::complex<float>*, int, const std::complex<float>*, int, const std::complex<float>&, std::complex<float>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:232:70: error: cannot convert ‘const std::complex<float>*’ to ‘const float*’ for argument ‘7’ to ‘void cblas_cgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, blasint, blasint, blasint, const float*, const float*, blasint, const float*, blasint, const float*, float*, blasint)’
                           K,  &alpha, A, lda, B,  ldb, &beta, C,  ldc);
                                                                      ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_gemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, const std::complex<double>&, const std::complex<double>*, int, const std::complex<double>*, int, const std::complex<double>&, std::complex<double>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:243:70: error: cannot convert ‘const std::complex<double>*’ to ‘const double*’ for argument ‘7’ to ‘void cblas_zgemm(CBLAS_ORDER, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, blasint, blasint, blasint, const double*, const double*, blasint, const double*, blasint, const double*, double*, blasint)’
                           K,  &alpha, A, lda, B,  ldb, &beta, C,  ldc);
                                                                      ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_gemv(CBLAS_ORDER, CBLAS_TRANSPOSE, int, int, const std::complex<float>&, const std::complex<float>*, int, const std::complex<float>*, int, const std::complex<float>&, std::complex<float>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:275:85: error: cannot convert ‘const std::complex<float>*’ to ‘const float*’ for argument ‘5’ to ‘void cblas_cgemv(CBLAS_ORDER, CBLAS_TRANSPOSE, blasint, blasint, const float*, const float*, blasint, const float*, blasint, const float*, float*, blasint)’
             cblas_cgemv(order, TransA, M, N, &alpha, A, lda, X, incX, &beta, Y, incY);
                                                                                     ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_gemv(CBLAS_ORDER, CBLAS_TRANSPOSE, int, int, const std::complex<double>&, const std::complex<double>*, int, const std::complex<double>*, int, const std::complex<double>&, std::complex<double>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:285:85: error: cannot convert ‘const std::complex<double>*’ to ‘const double*’ for argument ‘5’ to ‘void cblas_zgemv(CBLAS_ORDER, CBLAS_TRANSPOSE, blasint, blasint, const double*, const double*, blasint, const double*, blasint, const double*, double*, blasint)’
             cblas_zgemv(order, TransA, M, N, &alpha, A, lda, X, incX, &beta, Y, incY);
                                                                                     ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_ger(CBLAS_ORDER, int, int, const std::complex<float>&, const std::complex<float>*, int, const std::complex<float>*, int, std::complex<float>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:295:72: error: cannot convert ‘const std::complex<float>*’ to ‘const float*’ for argument ‘4’ to ‘void cblas_cgeru(CBLAS_ORDER, blasint, blasint, const float*, const float*, blasint, const float*, blasint, float*, blasint)’
             cblas_cgeru (order,  M, N, &alpha, X, incX, Y, incY, A, lda);
                                                                        ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_ger(CBLAS_ORDER, int, int, const std::complex<double>&, const std::complex<double>*, int, const std::complex<double>*, int, std::complex<double>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:303:72: error: cannot convert ‘const std::complex<double>*’ to ‘const double*’ for argument ‘4’ to ‘void cblas_zgeru(CBLAS_ORDER, blasint, blasint, const double*, const double*, blasint, const double*, blasint, double*, blasint)’
             cblas_zgeru (order,  M, N, &alpha, X, incX, Y, incY, A, lda);
                                                                        ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_gerc(CBLAS_ORDER, int, int, const std::complex<float>&, const std::complex<float>*, int, const std::complex<float>*, int, std::complex<float>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:329:72: error: cannot convert ‘const std::complex<float>*’ to ‘const float*’ for argument ‘4’ to ‘void cblas_cgerc(CBLAS_ORDER, blasint, blasint, const float*, const float*, blasint, const float*, blasint, float*, blasint)’
             cblas_cgerc (order,  M, N, &alpha, X, incX, Y, incY, A, lda);
                                                                        ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘void dlib::blas_bindings::cblas_gerc(CBLAS_ORDER, int, int, const std::complex<double>&, const std::complex<double>*, int, const std::complex<double>*, int, std::complex<double>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:337:72: error: cannot convert ‘const std::complex<double>*’ to ‘const double*’ for argument ‘4’ to ‘void cblas_zgerc(CBLAS_ORDER, blasint, blasint, const double*, const double*, blasint, const double*, blasint, double*, blasint)’
             cblas_zgerc (order,  M, N, &alpha, X, incX, Y, incY, A, lda);
                                                                        ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘std::complex<float> dlib::blas_bindings::cblas_dot(int, const std::complex<float>*, int, const std::complex<float>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:361:57: error: cannot convert ‘const std::complex<float>*’ to ‘const float*’ for argument ‘2’ to ‘void cblas_cdotu_sub(blasint, const float*, blasint, const float*, blasint, openblas_complex_float*)’
             cblas_cdotu_sub(N, X, incX, Y, incY, &result);
                                                         ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘std::complex<double> dlib::blas_bindings::cblas_dot(int, const std::complex<double>*, int, const std::complex<double>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:370:57: error: cannot convert ‘const std::complex<double>*’ to ‘const double*’ for argument ‘2’ to ‘void cblas_zdotu_sub(blasint, const double*, blasint, const double*, blasint, openblas_complex_double*)’
             cblas_zdotu_sub(N, X, incX, Y, incY, &result);
                                                         ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘std::complex<float> dlib::blas_bindings::cblas_dotc(int, const std::complex<float>*, int, const std::complex<float>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:381:57: error: cannot convert ‘const std::complex<float>*’ to ‘const float*’ for argument ‘2’ to ‘void cblas_cdotc_sub(blasint, const float*, blasint, const float*, blasint, openblas_complex_float*)’
             cblas_cdotc_sub(N, X, incX, Y, incY, &result);
                                                         ^
/usr/include/dlib/matrix/matrix_blas_bindings.h: In function ‘std::complex<double> dlib::blas_bindings::cblas_dotc(int, const std::complex<double>*, int, const std::complex<double>*, int)’:
/usr/include/dlib/matrix/matrix_blas_bindings.h:390:57: error: cannot convert ‘const std::complex<double>*’ to ‘const double*’ for argument ‘2’ to ‘void cblas_zdotc_sub(blasint, const double*, blasint, const double*, blasint, openblas_complex_double*)’
             cblas_zdotc_sub(N, X, incX, Y, incY, &result);

```

## Steps to Reproduce
```
#include <caffe/caffe.hpp>
#include "dlib/image_io.h"
#include "dlib/image_processing.h"
#include "dlib/image_processing/frontal_face_detector.h"
#include "dlib/opencv.h"

```
Include above header files and compiles the code!! (Using CMake to compile)

* **Version**: (Pulled from master branch today)
* **Where did you get dlib**: Github repo
* **Platform**: 

```
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

* **Compiler**: gcc 7.3

**Comment by davisking** [comment]
Those steps to reproduce are not complete.  What exactly do you do to make this happen?

**Comment by achalshah20** [comment]
Including caffe.hpp after dlib headers fixed the issue. Not sure what part from caffe is messing up dlib.

**Comment by davisking** [comment]
It's because there is some version of the cblas header on your computer that defines the cblas function signatures different than normal. I just pushed a change to github that should make this not matter.  Can you try it and see if it makes the error go away?

**Comment by cchadowitz-pf** [comment]
I know this is old, but I ran into what appears to be a similar or related issue when building on Ubuntu 18.04 with gcc 7.4, using the 19.18 release.
```
dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h: In function 'std::complex<float> dlib::blas_bindings::cblas_dot(int, const std::complex<float>*, int, const std::complex<float>*, int)':
dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h:359:81: error: cannot convert 'float*' to 'openblas_complex_float* {aka __complex__ float*}' for argument '6' to 'void cblas_cdotu_sub(blasint, const float*, blasint, const float*, blasint, openblas_complex_float*)'
             cblas_cdotu_sub(N, (float*)X, incX, (float*)Y, incY, (float*)&result);
                                                                                 ^
dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h: In function 'std::complex<double> dlib::blas_bindings::cblas_dot(int, const std::complex<double>*, int, const std::complex<double>*, int)':
dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h:368:84: error: cannot convert 'double*' to 'openblas_complex_double* {aka __complex__ double*}' for argument '6' to 'void cblas_zdotu_sub(blasint, const double*, blasint, const double*, blasint, openblas_complex_double*)'
             cblas_zdotu_sub(N, (double*)X, incX, (double*)Y, incY, (double*)&result);
                                                                                    ^
dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h: In function 'std::complex<float> dlib::blas_bindings::cblas_dotc(int, const std::complex<float>*, int, const std::complex<float>*, int)':
dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h:379:81: error: cannot convert 'float*' to 'openblas_complex_float* {aka __complex__ float*}' for argument '6' to 'void cblas_cdotc_sub(blasint, const float*, blasint, const float*, blasint, openblas_complex_float*)'
             cblas_cdotc_sub(N, (float*)X, incX, (float*)Y, incY, (float*)&result);
                                                                                 ^
dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h: In function 'std::complex<double> dlib::blas_bindings::cblas_dotc(int, const std::complex<double>*, int, const std::complex<double>*, int)':
dlib/build/include/dlib/data_io/../matrix/matrix_blas_bindings.h:388:84: error: cannot convert 'double*' to 'openblas_complex_double* {aka __complex__ double*}' for argument '6' to 'void cblas_zdotc_sub(blasint, const double*, blasint, const double*, blasint, openblas_complex_double*)'
             cblas_zdotc_sub(N, (double*)X, incX, (double*)Y, incY, (double*)&result);
                                                                                    ^
```

I am building caffe as well, and I haven't yet determined if changing the include order resolves this, but at the very least it seems like the change from April 2018 didn't resolve it on its own (I'm guessing b95cb7d4a108360f53c7ad38fec49dcf220a7c40 is the change in question).

**Comment by davisking** [comment]
You could add to cblas_constants.h a CBLAS_DOUBLE_TYPE and CBLAS_FLOAT_TYPE and make the dlib headers use those instead of `(double*)` like is in there now.  You would need to use the preprocessor to decide how to set `CBLAS_DOUBLE_TYPE`, but it shouldn't be a big deal.

**Comment by cchadowitz-pf** [comment]
Interesting - to be clear, you're saying to use the preprocessor to determine the blas library in use and set it accordingly for that? I did figure out that changing `(double*)` to `(openblas_complex_double*)` resolved it while using openblas, but that obviously wouldn't work with other blas libraries. I assume for those `(double*)` would be fine.

**Comment by cchadowitz-pf** [comment]
So I tried to do that in #1914, which works in Ubuntu 18.04 with openblas 0.2.20 (from `libopenblas-dev`), but it breaks in Ubuntu 16.04 with openblas 0.2.18.
```
[ 23%] Building CXX object dlib/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
In file included from /home/cchadowitz/dlib/dlib/dlib/data_io/../geometry/../matrix/matrix_trsm.h:6:0,
                 from /home/cchadowitz/dlib/dlib/dlib/data_io/../geometry/../matrix/matrix_lu.h:11,
                 from /home/cchadowitz/dlib/dlib/dlib/data_io/../geometry/../matrix/matrix_la.h:13,
                 from /home/cchadowitz/dlib/dlib/dlib/data_io/../geometry/../matrix.h:11,
                 from /home/cchadowitz/dlib/dlib/dlib/data_io/../geometry/point_transforms.h:9,
                 from /home/cchadowitz/dlib/dlib/dlib/data_io/../geometry.h:10,
                 from /home/cchadowitz/dlib/dlib/dlib/data_io/image_dataset_metadata.h:8,
                 from /home/cchadowitz/dlib/dlib/dlib/data_io/image_dataset_metadata.cpp:6:
/home/cchadowitz/dlib/dlib/dlib/data_io/../geometry/../matrix/matrix_blas_bindings.h: In function ‘std::complex<float> dlib::blas_bindings::cblas_dot(int, const std::complex<float>*, int, const std::complex<float>*, int)’:
/home/cchadowitz/dlib/dlib/dlib/data_io/../geometry/../matrix/cblas_constants.h:9:26: error: ‘openblas_complex_float’ was not declared in this scope
 #define CBLAS_FLOAT_TYPE openblas_complex_float
```
(and so on for the other cases where I made the change)

I suspect it's something to do with the `#include <cblas.h>` and either it's changed between v0.2.18 and v0.2.20 or it's finding a different one to include. I'm going to try building with my changes in a clean Ubuntu 16.04 docker container just to be sure it's not that last possibility.

**Comment by cchadowitz-pf** [comment]
Ok, even in a clean 16.04 docker container, I have the same build error.

**Comment by barracuda156** [comment]
Has that been ever resolved?
