### ISSUE TITLE
compilation failed for landmark detection example with gcc 4.9.3

### ISSUE THREAD

**Issue by Puneetsharma030** [davisking/dlib#388]
Hi,

I am trying to compile the landmark detection example "face_landmark_detection_ex.cpp" on Linux ARM with the compiler version GCC 4.9.3. The compiler is complaining for "call_once" function. Here is the log

In file included from /usr/include/c++/4.9/future:39:0,
                 from src/dlib/image_processing/../image_transforms/../threads/async.h:11,
                 from src/dlib/image_processing/../image_transforms/../threads/parallel_for_extension.h:9,
                 from src/dlib/image_processing/../image_transforms/../threads.h:24,
                 from src/dlib/image_processing/../image_transforms/random_cropper.h:7,
                 from src/dlib/image_processing/../image_transforms.h:28,
                 from src/dlib/image_processing/scan_image_boxes.h:12,
                 from src/dlib/image_processing/setup_hashed_features.h:8,
                 from src/dlib/image_processing.h:17,
                 from src/face_landmark_detection_ex.cpp:43:
/usr/include/c++/4.9/mutex:703:70: error: macro "call_once" passed 3 arguments, but takes just 2
       call_once(once_flag& __once, _Callable&& __f, _Args&&... __args);
                                                                      ^
/usr/include/c++/4.9/mutex:731:68: error: macro "call_once" passed 3 arguments, but takes just 2
     call_once(once_flag& __once, _Callable&& __f, _Args&&... __args)
                                                                    ^
In file included from src/dlib/image_processing/../image_transforms/../threads/async.h:11:0,
                 from src/dlib/image_processing/../image_transforms/../threads/parallel_for_extension.h:9,
                 from src/dlib/image_processing/../image_transforms/../threads.h:24,
                 from src/dlib/image_processing/../image_transforms/random_cropper.h:7,
                 from src/dlib/image_processing/../image_transforms.h:28,
                 from src/dlib/image_processing/scan_image_boxes.h:12,
                 from src/dlib/image_processing/setup_hashed_features.h:8,
                 from src/dlib/image_processing.h:17,
                 from src/face_landmark_detection_ex.cpp:43:
/usr/include/c++/4.9/future:372:23: error: macro "call_once" passed 5 arguments, but takes just 2
             ref(__set));
                       ^
/usr/include/c++/4.9/future:1515:75: error: macro "call_once" passed 3 arguments, but takes just 2
     void _M_join() { std::call_once(_M_once, &thread::join, ref(_M_thread)); }
                                                                           ^
In file included from /usr/include/c++/4.9/future:39:0,
                 from src/dlib/image_processing/../image_transforms/../threads/async.h:11,
                 from src/dlib/image_processing/../image_transforms/../threads/parallel_for_extension.h:9,
                 from src/dlib/image_processing/../image_transforms/../threads.h:24,
                 from src/dlib/image_processing/../image_transforms/random_cropper.h:7,
                 from src/dlib/image_processing/../image_transforms.h:28,
                 from src/dlib/image_processing/scan_image_boxes.h:12,
                 from src/dlib/image_processing/setup_hashed_features.h:8,
                 from src/dlib/image_processing.h:17,
                 from src/face_landmark_detection_ex.cpp:43:
/usr/include/c++/4.9/mutex:703:7: error: variable or field 'call_once' declared void
       call_once(once_flag& __once, _Callable&& __f, _Args&&... __args);
       ^
/usr/include/c++/4.9/mutex:731:5: error: variable or field 'call_once' declared void
     call_once(once_flag& __once, _Callable&& __f, _Args&&... __args)
     ^
/usr/include/c++/4.9/mutex:734:7: error: expected primary-expression before 'auto'
       auto __bound_functor = std::__bind_simple(std::forward<_Callable>(__f),
       ^
/usr/include/c++/4.9/mutex:734:7: error: expected '}' before 'auto'
/usr/include/c++/4.9/mutex:736:7: error: '__once_callable' does not name a type
       __once_callable = &__bound_functor;
       ^
/usr/include/c++/4.9/mutex:737:7: error: '__once_call' does not name a type
       __once_call = &__once_call_impl<decltype(__bound_functor)>;
       ^
/usr/include/c++/4.9/mutex:746:33: error: '__once' was not declared in this scope
       int __e = __gthread_once(&__once._M_once, &__once_proxy);
                                 ^
/usr/include/c++/4.9/mutex:753:7: error: expected unqualified-id before 'if'
       if (__e)
       ^
/usr/include/c++/4.9/mutex:760:1: error: expected declaration before '}' token
 } // namespace
 ^

Is it a known bug with gcc 4.9.3? Previously I was using dlib version 18.14 with the same compiler version and had no such issue compiling the landmark example.

**Comment by davisking** [comment]
Those errors all all from header files in /usr/include/c++, not from parts of dlib.  So maybe your compiler is broken. Like this

```
/usr/include/c++/4.9/mutex:703:70: error: macro "call_once" passed 3 arguments, but takes just 2
call_once(once_flag& __once, _Callable&& __f, _Args&&... __args);
```

Dlib doesn't call call_once.  It looks like that error is entirely within the system header files.

**Comment by stefan-it** [comment]
ARM64 with GCC *6.2* works fine :)

**Comment by Puneetsharma030** [comment]
I am using arm7l (32 bit) on ubuntu mate 1.10.2 with gcc 4.9.3

**Comment by stefan-it** [comment]
I tried it on Ubuntu 15.10 with GCC 4.9.3 (but on ARM64): compilation worked without any problems. So could you try another GCC (like the 5.x series)?

**Comment by Puneetsharma030** [comment]
My project requirements restrict me to use only gcc 4.9. I will try to make a fresh install and try again!

**Comment by davisking** [comment]
Dlib will work fine with gcc at least as old as 4.8.  So that should be fine.  But like I was saying before, it looks like your gcc install is just broken and this problem doesn't have anything to do with dlib.
