### ISSUE TITLE
compile dlib in ubuntu 16.04 with cuda 9.0 and cudnn 7.0 (Configuring incomplete, errors occurred!)

### ISSUE THREAD

**Issue by ghimiredhikura** [davisking/dlib#1131]
I am trying to compile dlib with cuda 9.0 (release 9.0, V9.0.176) and cudnn 7.0, but it gives error. It looks like dlib is only configured for cuda 8.0. I want help to compile with cuda 9.0. Any help please

## Expected Behavior
I am trying to compile example programs, but there is some compilation error. 

## Current Behavior

ghimire@keti:~/dlib-19.9/examples$ mkdir build
ghimire@keti:~/dlib-19.9/examples$ cd build/
ghimire@keti:~/dlib-19.9/examples/build$ ls
ghimire@keti:~/dlib-19.9/examples/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for png_create_read_struct
-- Looking for png_create_read_struct - found
-- Looking for jpeg_read_header
-- Looking for jpeg_read_header - found
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   Found lapack, version 3.6.0
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Found LAPACK library
-- Found BLAS library
-- Looking for cblas_ddot
-- Looking for cblas_ddot - found
-- Looking for sgesv
-- Looking for sgesv - not found
-- Looking for sgesv_
-- Looking for sgesv_ - found
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.5") 
-- Looking for cuDNN install...
-- Found cuDNN: /usr/local/cuda/lib64/libcudnn.so
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Checking if you have the right version of cuDNN installed.
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CUDA: Found unsuitable version "9.0", but required is exact
  version "8.0" (found /usr/local/cuda)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindCUDA.cmake:949 (find_package_handle_standard_args)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:86 (find_package)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:105 (find_host_package)
  CMakeLists.txt:149 (find_package)

-- Configuring incomplete, errors occurred!

See also "/home/ghimire/dlib-19.9/examples/build/CMakeFiles/CMakeOutput.log".
See also "/home/ghimire/dlib-19.9/examples/build/CMakeFiles/CMakeError.log".

## Steps to Reproduce

OS: Ubuntu 16.04
CUDA Version: 9.0
cudnn: 7.0
dlib: 19.9

I followed steps in http://dlib.net/compile.html

**Comment by davisking** [comment]
I just updated to cuda 9.1 on Ubuntu 16.04 and it worked without any
issue.  Maybe there is a bug in 9.0 and you need to update to 9.1. I notice
they released 9.1 very quickly after 9.0.  Or maybe your cuda install is
broken and you need to reinstall.

**Comment by ghimiredhikura** [comment]
Dear Davis King, 

Thank your for your reply. I have one more question. 
Can you please tell me how can I disable CUDA support while compiling from C++. 

cd examples
mkdir build
cd build
cmake ..
cmake --build . --config Release

Thank you in advance.

**Comment by davisking** [comment]
It's a cmake option. DLIB_USE_CUDA, you can set it to off via cmake -D

**Comment by mljli** [comment]
This is required by OpenCV, not Dlib. You should rebuild OpenCV with CUDA 9.0.
