### ISSUE TITLE
error: redeclaration of ‘const long unsigned int& block_size’

### ISSUE THREAD

**Issue by gmh14** [davisking/dlib#625]
/home/guominghuao/workspace/dlib/dlib/../dlib/image_processing/shape_predictor_trainer.h:415:80: error: redeclaration of ‘const long unsigned int& block_size’
                     const unsigned long block_end =  std::min(num, block_begin + block_size);
/home/guominghuao/workspace/dlib/dlib/../dlib/image_processing/shape_predictor_trainer.h:414:61: note: ‘const long unsigned int& block_size’ previously declared here
                     const unsigned long block_begin = block * block_size;

I got this error when I compiled dlib Python API using the command 'python setup.py install'. I looked into the file 'shape_predictor_trainer.h' and did not find anything wrong. Does this error occur because of my g++ version? Mine is 5.1.0.

**Comment by davisking** [comment]
I don't know.  You probably have something wrong with your system since that error doesn't make any sense.  It's not the gcc version though.

**Comment by gmh14** [comment]
Maybe you are right. I have this problem on Fedora while Ubuntu is ok.

**Comment by davisking** [comment]
It's pretty likely that there is some #define on your system that's messing
it up.  Like maybe someone has #defined the word block_size to a number or
something silly like that.  This kind of bizarre error is almost always due
to a #define.

**Comment by davisking** [comment]
No problem.  Is the #define coming from something on Fedora's normal
install?  Like, is this something that needs to be worked around so other
Fedora users don't start posting about this? :)

**Comment by gmh14** [comment]
I find another reason for the problem. It may because of the gcc version. (After I corrected the system #define, the problem still exists.) When I converted the variable 'block_size' from the type 'const' to a non-const type, the problem disappeared. Maybe the compiler causes the problem.

**Comment by davisking** [comment]
Huh, well, I won't worry about it unless other people starting reporting issues on Fedora.

**Comment by gmh14** [comment]
Ahhhha, thank you anyway!

**Comment by ramPkrish** [comment]
I also encountered the same issue, and as suggested by gmh14, I had to remove 'const' keyword for successful compilation.  I am using Fedora as well.

**Comment by davisking** [comment]
What exactly did you guys change?

**Comment by ramPkrish** [comment]
I had to change "const unsigned long block_size" to "unsigned long block_size" both at line numbers 829 and 958 in ../dlib/image_processing/shape_predictor.h to make it compile.

**Comment by ramPkrish** [comment]
[ 24%] Building CXX object CMakeFiles/dtest.dir/face.cpp.o
In file included from /home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing.h:22:0,
                 from /home/rpk/dlib/dlib-19.4/dlib/test/face.cpp:6:
/home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing/shape_predictor.h: In instantiation of ‘dlib::shape_predictor_trainer::make_regression_tree(dlib::thread_pool&, std::vector<dlib::shape_predictor_trainer::training_sample<feature_type> >&, const std::vector<dlib::vector<float, 2l> >&) const::<lambda(long unsigned int)> [with feature_type = unsigned char]’:
/home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing/shape_predictor.h:839:25:   required from ‘struct dlib::shape_predictor_trainer::make_regression_tree(dlib::thread_pool&, std::vector<dlib::shape_predictor_trainer::training_sample<feature_type> >&, const std::vector<dlib::vector<float, 2l> >&) const [with feature_type = unsigned char]::<lambda(long unsigned int)>’
/home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing/shape_predictor.h:832:29:   required from ‘dlib::impl::regression_tree dlib::shape_predictor_trainer::make_regression_tree(dlib::thread_pool&, std::vector<dlib::shape_predictor_trainer::training_sample<feature_type> >&, const std::vector<dlib::vector<float, 2l> >&) const [with feature_type = unsigned char]’
/home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing/shape_predictor.h:716:21:   required from ‘dlib::shape_predictor dlib::shape_predictor_trainer::train(const image_array&, const std::vector<std::vector<dlib::full_object_detection> >&) const [with image_array = dlib::array<dlib::array2d<unsigned char> >]’
/home/rpk/dlib/dlib-19.4/dlib/test/face.cpp:66:63:   required from here
/home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing/shape_predictor.h:835:80: error: redeclaration of ‘const long unsigned int& block_size’
                     const unsigned long block_end =  std::min(num, block_begin + block_size);
                                                                                ^
/home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing/shape_predictor.h:834:61: note: ‘const long unsigned int& block_size’ previously declared here
                     const unsigned long block_begin = block * block_size;
                                                             ^
/home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing/shape_predictor.h: In instantiation of ‘dlib::impl::regression_tree dlib::shape_predictor_trainer::make_regression_tree(dlib::thread_pool&, std::vector<dlib::shape_predictor_trainer::training_sample<feature_type> >&, const std::vector<dlib::vector<float, 2l> >&) const [with feature_type = unsigned char]’:
/home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing/shape_predictor.h:716:21:   required from ‘dlib::shape_predictor dlib::shape_predictor_trainer::train(const image_array&, const std::vector<std::vector<dlib::full_object_detection> >&) const [with image_array = dlib::array<dlib::array2d<unsigned char> >]’
/home/rpk/dlib/dlib-19.4/dlib/test/face.cpp:66:63:   required from here
/home/rpk/dlib/dlib-19.4/dlib/../dlib/image_processing/shape_predictor.h:832:50: sorry, unimplemented: non-trivial designated initializers not supported
                 parallel_for(tp, 0, num_workers, [&](unsigned long block)
                                                  ^
In file included from /home/rpk/dlib/dlib-19.4/dlib/../dlib/logger/../threads.h:24:0,
                 from /home/rpk/dlib/dlib-19.4/dlib/../dlib/logger/logger_kernel_1.h:6,
                 from /home/rpk/dlib/dlib-19.4/dlib/../dlib/logger.h:6,
                 from /home/rpk/dlib/dlib-19.4/dlib/test/tester.h:9,
                 from /home/rpk/dlib/dlib-19.4/dlib/test/face.cpp:4:
/home/rpk/dlib/dlib-19.4/dlib/../dlib/logger/../threads/parallel_for_extension.h:255:10: error: ‘void dlib::parallel_for(dlib::thread_pool&, long int, long int, const T&, long int) [with T = dlib::shape_predictor_trainer::make_regression_tree(dlib::thread_pool&, std::vector<dlib::shape_predictor_trainer::training_sample<feature_type> >&, const std::vector<dlib::vector<float, 2l> >&) const [with feature_type = unsigned char]::<lambda(long unsigned int)>]’, declared using local type ‘const dlib::shape_predictor_trainer::make_regression_tree(dlib::thread_pool&, std::vector<dlib::shape_predictor_trainer::training_sample<feature_type> >&, const std::vector<dlib::vector<float, 2l> >&) const [with feature_type = unsigned char]::<lambda(long unsigned int)>’, is used but never defined [-fpermissive]
     void parallel_for (
          ^
CMakeFiles/dtest.dir/build.make:998: recipe for target 'CMakeFiles/dtest.dir/face.cpp.o' failed
gmake[2]: *** [CMakeFiles/dtest.dir/face.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dtest.dir/all' failed
gmake[1]: *** [CMakeFiles/dtest.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
gmake: *** [all] Error 2
[rpk@localhost build]$

**Comment by davisking** [comment]
Try renaming the variable to something else. I suspect the issue is that block_size is #defined to const int& block_size and that's the real issue.

**Comment by ramPkrish** [comment]
Renaming block_size didn't help.

![dliberror1](https://user-images.githubusercontent.com/29481766/27230055-dd5fb874-52a5-11e7-8ae1-2660f0c3981f.png)

**Comment by davisking** [comment]
Huh, what about some of the other things in the area?  I'm pretty convinced
this is due to a #define messing things up.  I mean, if it isn't then it's
a pretty serious bug in gcc.

**Comment by ramPkrish** [comment]
The issue starts from dlib version 19.1 where this 'block_size' variable is introduced in 'shape_predictor.h'. But removing the 'const' keyword avoids the compilation error. Why it is so? I was working with 19.0, and it compiles perfectly even now.

**Comment by davisking** [comment]
Try renaming some other things and see if that avoids a #define name clash.
