### ISSUE TITLE
Visual Studio linker error when compiling dlib 19.13 with CUDA 9.2 in release mode

### ISSUE THREAD

**Issue by yjtan118** [davisking/dlib#1523]
## Current Behavior
Managed to compile dlib 19.13 with DLIB_USE_CUDA directives turned on in Visual Studio 2017 debug mode. Expecting that Release mode should compile without issues too, but am getting the following linker error:

Error	LNK2005	USER_ERROR__inconsistent_build_configuration__see_dlib_faq_1_ already defined in source.obj	Project	\dlib19.13.0_release_64bit_msvc1912.lib(test_for_odr_violations.obj)

Error	LNK1169	one or more multiply defined symbols found	Project	\x64\Release\Project.exe

## Steps to Reproduce
The linker dependencies in my VS 2017 look something like these:
D:\Lib\dlib\build\dlib\Release\dlib19.13.0_release_64bit_msvc1912.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudnn.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudart_static.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\curand.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cusolver.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cublas.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudadevrt.lib

* **Version**:  dlib 19.13, CUDA 9.2
* **Platform**: Windows 10, 64 bit
* **Compiler**: Visual Studio 2017 Professional ver 15.8.6

I managed to get this compiled in Release mode, by turning on ENABLE_ASSERTS preprocessor directive. Am wondering is this the right way of getting past the VS linker error with CUDA 9.2. Would the latest version of dlib fix this? Appreciate any comments. Thanks.

**Comment by davisking** [comment]
No, this is not the right thing to do.  Did you read the FAQ suggested by the error: http://dlib.net/faq.html#WhydoIgetUSERERRORinconsistentbuildconfigurationseedlibfaq1?  

I would be a little surprised if you didn't also get the other error directing you to http://dlib.net/faq.html#WhydoIgetUSERERRORinconsistentbuildconfigurationseedlibfaq2 as well.

**Comment by yjtan118** [comment]
Yes, read those FAQs earlier, but didn't get much hints from them. I've done a quick check - it seems that the debug and release libraries are correctly linked. And am pretty sure I've built dlib the proper way from cmake and Visual Studio. Anyhow, the program is working perfectly fine, except that I need to include the ENABLE_ASSERTS for release mode. It just seemed strange that debug is compiling fine but not on release...

**Comment by davisking** [comment]
You must be linking to a .lib file compiled with asserts enabled if you are getting this error.  I don't see how it could happen any other way.

**Comment by davisking** [comment]
Well, unless this is some kind of cuda/visual studio bug.  Does this only happen when you try to use cuda?

**Comment by yjtan118** [comment]
Yup, it only happens when DLIB_USE_CUDA is enabled and only in Release configuration. It compiles successfully when DLIB_USE_CUDA is removed. Below is the full list of directives that I'm turning on. 

DLIB_JPEG_SUPPORT
DLIB_JPEG_STATIC
DLIB_USE_CUDA
DLIB_USE_BLAS
DLIB_USE_LAPACK
USE_AVX_INSTRUCTIONS
USE_SSE4_INSTRUCTIONS

For the list of .lib that I'm linking to:
D:\Lib\OpenCVBuild\lib\Release\opencv_imgproc342.lib
...more opencv release lib
D:\Lib\dlib\build\dlib\Release\dlib19.13.0_release_64bit_msvc1912.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudnn.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cudart_static.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\curand.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cusolver.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\lib\x64\cublas.lib
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.3.210\windows\mkl\lib\intel64_win\mkl_core_dll.lib
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.3.210\windows\mkl\lib\intel64_win\mkl_intel_lp64_dll.lib

**Comment by davisking** [comment]
Are you adding dlib/all/source.cpp to your project?

**Comment by yjtan118** [comment]
Yes, source.cpp is added to the VS project.

**Comment by davisking** [comment]
That’s why this is happening. Don’t do that.  You can’t link the the lib and then also stick the same code from the lib file into the project. That’s why you get errors about things being defined two times.

**Comment by yjtan118** [comment]
hmm...if I do away with the lib file (which is precompiled separately), i will get a bunch of linker errors.  Make me wonder if i have built dlib even correctly from the beginning. i recalled not using cmake --build, but i have used visual studio solution to build it after getting the generated solution file from cmake. i'm trying to rebuild dlib again using cmake --build, and will just need to resolve the cmake test cuda error. And hopefully after this, it will be a much cleaner one. If you happen to know a fast fix for the below error, just drop me a note. Thanks!

-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- *****************************************************************************************************************
-- *** CUDA was found but your compiler failed to compile a simple CUDA program so dlib isn't going to use CUDA.
-- *** The output of the failed CUDA test compile is shown below:
-- ***   Change Dir: D:/Lib/dlib/build/dlib/cuda_test_build
   ***
   ***   Run Build Command:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional/MSBuild/15.0/Bin/MSBuild.exe" "ALL_BUILD.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=15.0"
   ***   Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
   ***   Copyright (C) Microsoft Corporation. All rights reserved.
   ***
   ***   Build started 10/24/2018 3:41:49 PM.
   ***   Project "D:\Lib\dlib\build\dlib\cuda_test_build\ALL_BUILD.vcxproj" on node 1 (default targets).
   ***   Project "D:\Lib\dlib\build\dlib\cuda_test_build\ALL_BUILD.vcxproj" (1) is building "D:\Lib\dlib\build\dlib\cuda_test_build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
   ***   PrepareForBuild:
   ***     Creating directory "x64\Debug\ZERO_CHECK\".
   ***     Creating directory "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
   ***   InitializeBuildStatus:
   ***     Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
   ***   CustomBuild:
   ***     Checking Build System
   ***     CMake does not need to re-run because D:/Lib/dlib/build/dlib/cuda_test_build/CMakeFiles/generate.stamp is up-to-date.
   ***   FinalizeBuildStatus:
   ***     Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
   ***     Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
   ***   Done Building Project "D:\Lib\dlib\build\dlib\cuda_test_build\ZERO_CHECK.vcxproj" (default targets).
   ***   Project "D:\Lib\dlib\build\dlib\cuda_test_build\ALL_BUILD.vcxproj" (1) is building "D:\Lib\dlib\build\dlib\cuda_test_build\cuda_test.vcxproj" (3) on node 1 (default targets).
   ***   PrepareForBuild:
   ***     Creating directory "cuda_test.dir\Debug\".
   ***     Creating directory "D:\Lib\dlib\build\dlib\cuda_test_build\Debug\".
   ***     Creating directory "cuda_test.dir\Debug\cuda_test.tlog\".
   ***   InitializeBuildStatus:
   ***     Creating "cuda_test.dir\Debug\cuda_test.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
   ***   ComputeCustomBuildOutput:
   ***     Creating directory "D:\Lib\dlib\build\dlib\cuda_test_build\CMakeFiles\cuda_test.dir\Debug\".
   ***   CustomBuild:
   ***     Building NVCC (Device) object CMakeFiles/cuda_test.dir/Debug/cuda_test_generated_cuda_test.cu.obj
   ***     CMake Error at cuda_test_generated_cuda_test.cu.obj.Debug.cmake:218 (message):
   ***       Error generating
   ***       **D:/Lib/dlib/build/dlib/cuda_test_build/CMakeFiles/cuda_test.dir//Debug/cuda_test_generated_cuda_test.cu.obj**
   ***
   ***
   ***   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [D:\Lib\dlib\build\dlib\cuda_test_build\cuda_test.vcxproj]
   ***   Done Building Project "D:\Lib\dlib\build\dlib\cuda_test_build\cuda_test.vcxproj" (default targets) -- FAILED.
   ***   Done Building Project "D:\Lib\dlib\build\dlib\cuda_test_build\ALL_BUILD.vcxproj" (default targets) -- FAILED.
   ***
   ***   Build FAILED.
   ***
   ***   "D:\Lib\dlib\build\dlib\cuda_test_build\ALL_BUILD.vcxproj" (default target) (1) ->
   ***   "D:\Lib\dlib\build\dlib\cuda_test_build\cuda_test.vcxproj" (default target) (3) ->
   ***   (CustomBuild target) ->
   ***     C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [D:\Lib\dlib\build\dlib\cuda_test_build\cuda_test.vcxproj]

**Comment by davisking** [comment]
You have to use a compiler that is supported by CUDA. So this isn't related to dlib.  If you read the documentation on NVIDIA's website you can find the list of supported compilers for each version of CUDA.

Also, http://dlib.net/compile.html contains detailed instructions for building and using dlib.  If you follow them I promise everything will build correctly.

**Comment by yjtan118** [comment]
My version of visual studio is already working fine with CUDA 9.2 projects. Supposed this is more of cmake issue then.

**Comment by davisking** [comment]
It’s not cmake. The newest visual studio update increments the visual studio version number checked by the cuda headers and is rejected by those checks, which are in cuda. If you update to cuda 10 it will work.

**Comment by yjtan118** [comment]
Interesting...thanks so much for the hints!

**Comment by yjtan118** [comment]
hi Davis, i've upgraded to CUDA 10, CMake 12.x and dlib 19.6 and able to get dlib compiled the right way by using source.cpp method. CUDA test projects have been tested to work fine with VS. dlib's build is perfect and is using CUDA. However, when DLIB_USE_CUDA directive is turned on, I'm getting a bunch of linker errors such as: 
1>source.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::memcpy(class dlib::gpu_data &,unsigned __int64,class dlib::gpu_data const &,unsigned __int64,unsigned __int64)" (?memcpy@dlib@@YAXAEAVgpu_data@1@_KAEBV21@11@Z)

The VS project is already linked to the CUDA 10.0 lib files.
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64\cudnn.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64\cudart.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64\curand.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64\cusolver.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64\cublas.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64\cudadevrt.lib

Any quick thoughts on what else is missing here?
Thanks.

**Comment by davisking** [comment]
Don't use all/source.cpp at all.  Instead, follow the instructions for using cmake here http://dlib.net/compile.html.

**Comment by DhiviJR** [comment]
I m using dlib v 19.17 trying to compile with visual studio 2015 ,cuda9.0
I followed the the steps mentioned in http://dlib.net/compile.html for visual studio build .
I included all headers and added source.cpp into my project. I am getting the same  linker errors as follows:

source.obj : error LNK2001: unresolved external symbol "void __cdecl dlib::memcpy(class dlib::gpu_data &,unsigned __int64,class dlib::gpu_data const &,unsigned __int64,unsigned __int64)" (?memcpy@dlib@@YAXAEAVgpu_data@1@_KAEBV21@11@Z)
