### ISSUE TITLE
CUDA ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives

### ISSUE THREAD

**Issue by MyraBaba** [davisking/dlib#1696]
@davisking 

I am working on the ubuntu with Qt 5.11.3 .  
I installed latest cuda and cudnn with the dlib 19.17

I compiled dlib as shared library : 
`cmake -DBUILD_SHARED_LIBS=1 -DUSE_AVX_INSTRUCTIONS=1 ..`
and 
`sudo make install`

when I try to compile the projects its giving below error: 
`main.o: In function _GLOBAL__sub_I_main.cpp': /data/Facial-/main.cpp:(.text.startup+0x39): undefined reference to USER_ERRO
R__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'
worker.o: In function _GLOBAL__sub_I_worker.cpp': /data/Facial-/worker.cpp:(.text.startup+0x39): undefined reference to USER_ER
ROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'
widget.o: In function _GLOBAL__sub_I_widget.cpp': /data/Facial-Z01-Saftas-MileSight-Commercial-v2__/widget.cpp:(.text.startup+0x39): undefined reference to USER_ER
ROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'
camera_02.o: In function _GLOBAL__sub_I_camera_02.cpp': /data/Facial-/camera_02.cpp:(.text.startup+0x39): undefined reference to USER
ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives
'
camera_01.o: In function _GLOBAL__sub_I_camera_01.cpp': /data/Facial-/camera_01.cpp:(.text.startup+0x39): undefined reference to USER
ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives
'
camera_03.o:/data/Facial-/camera_03.cpp:(.text.startup+0x39): more undefined r
eferences to `USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_prepro
cessor_directives_' follow
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

When I switch to the dlib 19.9 and I can compile without Cuda support no problem.

What is  `undefined reference to USER
ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives`

error ? 

is this due to multiple dlib in the path somehow ? have you ever experienced before ?

**Comment by davisking** [comment]
That error is telling you that you have messed up your build system
somehow.  I don't know what you did.  You haven't posted what you did.  You
need to post a complete set of steps that someone can type to reproduce
your problem if you want help.
