### ISSUE TITLE
libx11-dev installed but missing ?

### ISSUE THREAD

**Issue by kalravibhor** [davisking/dlib#872]
Hi, I am working on a Mac OS X 10.12.6 machine. I managed to install XQuartz from the official website. However post installing dlib (using Homebrew) and trying to run the new MMOD CNN Face Detection (using g++ and c++-11 support), I get the following error.

```
/usr/local/include/dlib/gui_core/gui_core_kernel_2.h:11:2: error: "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code. Turn
      DLIB_NO_GUI_SUPPORT off if you want to use it."
#error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
 ^
/usr/local/include/dlib/gui_core/gui_core_kernel_2.h:12:2: error: "Also make sure you have libx11-dev installed on your system"
#error "Also make sure you have libx11-dev installed on your system"
 ^
2 errors generated.
```
I managed to go through all the links on the first page of Google search results but found no answers that work. Most of them suggest installing XQuartz and Dlib from scratch, which I did multiple times with no success. Can someone share some insight as to what what is happening ? Is my dlib installation unable to find libx11-dev ? If so, how do I correct it ?

Thanks in advance.

**Comment by davisking** [comment]
Don't use homebrew.  Whatever copy of dlib is in homebrew is configured to
not use X11.

**Comment by kalravibhor** [comment]
Thanks. Downloading and following the instructions in the README worked.

**Comment by fernandezmanuel** [comment]
> Thanks. Downloading and following the instructions in the README worked.

Could you tell me how did you add the libraries in Xcode if you didn't use the ones from Cellar/Homebrew? 

Thanks!
